# For more info on HTTP files go to https://aka.ms/vs/httpfile

POST http://localhost:5000/submit-order
Content-Type: application/json

{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "message/send",
    "params": {
       "message": {
            "messageId": "abc-def",
            "role": "user",
            "parts": [
                {
                    "kind": "text",
                    "text": "I want a black coffee, cappuccino and 2 cake pops."
                }
            ]
        }
    }
}

###
