<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
    <AspireVersion>13.0.0</AspireVersion>
    <MafVersion>1.0.0-preview.251016.1</MafVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspire.Hosting.AppHost" Version="$(AspireVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.0.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0-rc.1" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0-rc.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0-rc.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0-rc.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.13.0" />
    <PackageVersion Include="Microsoft.Identity.Web" Version="4.0.1" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.10.3" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>
  <ItemGroup Label="AI">
    <PackageVersion Include="A2A.AspNetCore" Version="0.3.3-preview" />
    <PackageVersion Include="ModelContextProtocol.AspNetCore" Version="0.4.0-preview.3" />
  </ItemGroup>
  <ItemGroup Label="MAF">
    <PackageVersion Include="Azure.Identity" Version="1.17.0" />
    <PackageVersion Include="Microsoft.Extensions.AI" Version="10.0.0" />
    <PackageVersion Include="Azure.AI.OpenAI" Version="2.5.0-beta.1" />
    <PackageVersion Include="Microsoft.Agents.AI" Version="1.0.0-preview.251110.2" />
    <PackageVersion Include="Microsoft.Agents.AI.OpenAI" Version="1.0.0-preview.251110.2" />
    <PackageVersion Include="Microsoft.Agents.AI.A2A" Version="1.0.0-preview.251110.2" />
    <PackageVersion Include="Microsoft.Agents.AI.AGUI" Version="1.0.0-preview.251110.2" />
    <PackageVersion Include="Microsoft.Agents.AI.DevUI" Version="1.0.0-preview.251110.2" />
    <PackageVersion Include="Microsoft.Agents.AI.Hosting.AGUI.AspNetCore" Version="1.0.0-preview.251110.2" />
    <PackageVersion Include="Microsoft.Agents.AI.Workflows" Version="1.0.0-preview.251110.2" />
  </ItemGroup>
  <ItemGroup Label="Web">
    <PackageVersion Include="System.Linq.Async" Version="6.0.3" />
    <PackageVersion Include="Microsoft.SemanticKernel.Core" Version="1.66.0" />
    <PackageVersion Include="Microsoft.SemanticKernel.Connectors.SqliteVec" Version="1.66.0-preview" />
  </ItemGroup>
</Project>
